### ISSUE TITLE
Unable to set 0 as a value of env var

### ISSUE THREAD

**Issue by bocharsky-bw** [sroze/companienv#5]
How can I set `false` as a value of environment variable? Before, I handled it with `0` value which was converted to `false` with `%env(bool:BOOL_ENV_VAR)%` Symfony feature. But now, when I set `0` during interactive mode of `./vendor/bin/companienv` it just re-ask a new value.

**Comment by sroze** [comment]
Hi @bocharsky-bw! Thank you for your feedback. You are right, and I've issued the pull-request #6 to fix this problem. Would you like to review it?

**Comment by sroze** [comment]
This has been fixed and released as part of [0.0.5](https://github.com/sroze/companienv/releases/tag/0.0.5).

**Comment by bocharsky-bw** [comment]
Hey @sroze ,

Thanks for the quick fix! Now it better, when I have `ENV_VAR=0` in `.env` file - it does not tell me "It looks like you are missing some configuration (1 variables)" message anymore, but I still can't set up `0` through interactive mode, i.e. when I have `ENV_VAR=` in `.env` file and run `./vendor/bin/companienv` - still can't put `0`, see screenshot:

<img width="883" alt="screen shot 2018-02-06 at 12 37 15" src="https://user-images.githubusercontent.com/3317635/35854967-88622250-0b3a-11e8-8713-be867c24ce1a.png">

**Comment by sroze** [comment]
@bocharsky-bw here we go: #9. Could you give a try and let me know if there is anything else? 🤔

**Comment by sroze** [comment]
The PR #9 has been released in [0.0.6](https://github.com/sroze/companienv/releases/tag/0.0.6)

**Comment by bocharsky-bw** [comment]
Works for me, thanks!
